version: 2
jobs:
  build:
    docker:
      - image: perl
    steps:
      - checkout
      - run:
          name: Test
          command: |
            chmod 700 ./test.sh
            ./test.sh
            cat ./serveur.log
            cat ./client.log
      - deploy:
         command: $DOCKERHUBTRIGGER
