version: 2
jobs:
  build:
    docker:
      - image: perl
    steps:
      - checkout
      - run:
          name: Lance Serveur
          command: perl ./serveur.pl >/dev/null 2>&1 &
      - run:
          name: Test
          command: |
            chmod 700 ./test.sh
            ./test.sh
